version: '2'
services:
  consula:
    image: consul
    tmpfs: /data
    cap_add:
     - NET_BIND_SERVICE
    expose:
     - "8300"
     - "8301"
     - "8302"
     - "8301/udp"
     - "8302/udp"
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:53"
     - "8600:53/udp"
    volumes:
     - ./consul/conf:/conf:ro
    command: agent -server -config-dir=/conf
  consulb:
    image: consul
    tmpfs: /data
    cap_add:
     - NET_BIND_SERVICE
    expose:
     - "8300"
     - "8301"
     - "8302"
     - "8301/udp"
     - "8302/udp"
     - "8400"
     - "53"
     - "53/udp"
     - "8500"
    volumes:
     - ./consul/conf:/conf:ro
    command: agent -server -config-dir=/conf -retry-join=consula
  consulc:
    image: consul
    tmpfs: /data
    cap_add:
     - NET_BIND_SERVICE
    expose:
     - "8300"
     - "8301"
     - "8302"
     - "8301/udp"
     - "8302/udp"
     - "8400"
     - "53"
     - "53/udp"
     - "8500"
    volumes:
     - ./consul/conf:/conf:ro
    command: agent -server -config-dir=/conf -retry-join=consula

  vault:
    image: vault
    cap_add:
     - IPC_LOCK
    ports:
     - "8200:8200"
    dns:
     - 172.18.0.2
     - 172.18.0.3
    volumes:
     - ./vault/conf:/conf:ro
     - ./vault/certs:/certs:ro
    environment:
     - VAULT_ADVERTISE_ADDR=https://172.18.0.5:8200
    command: server -config=/conf
    depends_on:
      - "consula"
      - "consulb"
      - "consulc"
  vault_standby:
    image: vault
    cap_add:
     - IPC_LOCK
    ports:
     - "8200"
    dns:
     - 172.18.0.2
     - 172.18.0.3
    volumes:
     - ./vault/conf:/conf:ro
     - ./vault/certs:/certs:ro
    environment:
     - VAULT_ADVERTISE_ADDR=https://172.18.0.6:8200
    command: server -config=/conf
    depends_on:
      - "consula"
      - "consulb"
      - "consulc"
      - "vault"
